# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 09:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
    ]
